-d /Users/drune/Developer/github.com/Specialist-PK/special20k/impl/gwsynthesis/special20k.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /Users/drune/Developer/github.com/Specialist-PK/special20k/src/tang20k.cst
-cfg /Users/drune/Developer/github.com/Specialist-PK/special20k/impl/pnr/device.cfg
-sdc /Users/drune/Developer/github.com/Specialist-PK/special20k/src/special20k.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
